//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindLab03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbpersonal
    {
        public int idpersonal { get; set; }
        public string nombre { get; set; }
        public string apellidom { get; set; }
        public string apellidop { get; set; }
        public string lugarnacimiento { get; set; }
        public string nacionalidad { get; set; }
        public string sexo { get; set; }
        public string estadocivil { get; set; }
    }
}
