//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindLab03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbstatep
    {
        public int idstate { get; set; }
        public string statename { get; set; }
        public string description { get; set; }
    }
}
